### ISSUE TITLE
vptree searches are slower than expected

### ISSUE THREAD

**Issue by cffk** [RickardSjogren/vptree#1]
Please see my [response](https://stackoverflow.com/questions/45440700/calculate-distance-to-shore-or-coastline-for-a-vessel/45480555#45480555) to a question on stackexchange.

I initially responded suggesting a solution using my C++ implementation of VP trees.  However since the question asked for a python implementation, I tried your vptree package.  As detailed in my response the mean number of distance calculations per lookup is about 7 times more than it *should* be.

The choices I made in my implementation of VP trees are given [here](https://geographiclib.sourceforge.io/1.49/nearest.html).

Here are the datasets I used in this experiment: [coast.txt](https://github.com/RickardSjogren/vptree/files/1203155/coast.txt) [vessels.txt](https://github.com/RickardSjogren/vptree/files/1203156/vessels.txt).

And here is the code (assumes that the python package geographiclib has been installed).
```
import numpy
import vptree
from geographiclib.geodesic import Geodesic

count = 0

def geoddist(p1, p2):
  # p1 = [lon1, lat1] in degrees
  # p2 = [lon2, lat2] in degrees
  global count
  count = count + 1
  return Geodesic.WGS84.Inverse(p1[1], p1[0], p2[1], p2[0])['s12']

coast = vptree.VPTree(numpy.loadtxt('coast.txt'), geoddist)
print('count=',count)
print('vessel closest-coast dist')
for v in numpy.loadtxt('vessels.txt'):
  c = coast.get_nearest_neighbor(v)
  print(list(v), list(c[1]), c[0])
print('count=',count)
```

**Comment by RickardSjogren** [comment]
Thank you for your feedback @cffk.

In its current state this implementation of the VPTree-search was stitched together based on tutorials in order for me to understand the algorithm a long time ago and later put together as a package. No attempts whatsoever to improve the performance have been done since it has been functional.

One possible culprit might be that this implementation [chooses vantage point at random](https://github.com/RickardSjogren/vptree/blob/master/vptree.py#L35) which I know is sub-optimal. I have not looked into other possible sources of poor performance.

I do not intend to be looking into this any time soon. Please feel free to contribute and submit a pull request if you know how to improve the performance!
