### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by albertoandreottiATgmail** [RickardSjogren/vptree#3]
When trying to create a VP tree with around 80k vectors, memory consumption grows to a few gigabytes, when all the data fits in ~32MB of memory.

**Comment by RickardSjogren** [comment]
Can you please provide a reproducible example @albertoandreottiATgmail? I have not encountered such issues myself.

I believe it is unlikely to be a memory leak since only python lists are passed to child trees. There will however be a memory overhead since new child VPTree-instances are created recursively to populate the tree.
